name: Checkout Build and Push Docker Image

on:
  push:
    branches:
      - main

CI:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USER }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: build docker image node
      run: |
        docker build . --file Dockerfile --tag super-app/node:${{ GITHUB_RUN_NUMBER }}-${{ git.sha }}
    
    # - name: Push Docker image to Docker Hub
    #   run: |
    #     docker push yourdockerhubusername/yourimagename:latest
