name: Checkout Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:

  CI:
    
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      - name: build docker image node
        run: |
          docker build -progress=plain . --file Dockerfile --tag super-app:${{ github.run_number }}-${{ github.sha }}
      
      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker push yourdockerhubusername/yourimagename:latest
